version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "Amjad50"
    assignees:
      - "Amjad50"
    commit-message:
      prefix: "cargo"
      include: "scope"

  - package-ecosystem: "cargo"
    directory: "/mizu-core"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "Amjad50"
    assignees:
      - "Amjad50"
    commit-message:
      prefix: "cargo"
      include: "scope"

  - package-ecosystem: "cargo"
    directory: "/save_state"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "Amjad50"
    assignees:
      - "Amjad50"
    commit-message:
      prefix: "cargo"
      include: "scope"

  - package-ecosystem: "cargo"
    directory: "/save_state_derive"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "Amjad50"
    assignees:
      - "Amjad50"
    commit-message:
      prefix: "cargo"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "Amjad50"
    assignees:
      - "Amjad50"
    commit-message:
      prefix: "ci"
      include: "scope"
